//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaaliyetAlani
    {
        public FaaliyetAlani()
        {
            this.MusteriFirmas = new HashSet<MusteriFirma>();
        }
    
        public int FaaliyetAlanID { get; set; }
        public string FaaliyetAlani1 { get; set; }
        public int MusteriID { get; set; }
    
        public virtual ICollection<MusteriFirma> MusteriFirmas { get; set; }
    }
}
