//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.Adres = new HashSet<Adre>();
            this.Emails = new HashSet<Email>();
            this.Telefons = new HashSet<Telefon>();
        }
    
        public int MusteriID { get; set; }
        public int TipID { get; set; }
    
        public virtual ICollection<Adre> Adres { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual MusteriTuru MusteriTuru { get; set; }
        public virtual MusteriBireysel MusteriBireysel { get; set; }
        public virtual MusteriFirma MusteriFirma { get; set; }
        public virtual ICollection<Telefon> Telefons { get; set; }
    }
}
