//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTuru
    {
        public MusteriTuru()
        {
            this.Musteris = new HashSet<Musteri>();
        }
    
        public int TipID { get; set; }
        public string TipAdi { get; set; }
    
        public virtual ICollection<Musteri> Musteris { get; set; }
    }
}
