//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBireysel
    {
        public MusteriBireysel()
        {
            this.BireyselUnvans = new HashSet<BireyselUnvan>();
        }
    
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TC { get; set; }
        public DateTime DogumTarihi { get; set; }
        public int MusteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual ICollection<BireyselUnvan> BireyselUnvans { get; set; }
    }
}
